## Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "test_126@email.com",
    "password": "aaaa_pwd"
}

### Sign user in
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "test_126@email.com",
    "password": "aaaa_pwd"
}

### Find a user with specifc id
GET http://localhost:3000/auth/2

### Find all users with matching email
GET http://localhost:3000/auth?email=test@email.com

### Remove user with specified ID
DELETE http://localhost:3000/auth/3

### Update user
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "email": "david_99@johnson.com",
    "password": "1234_pwd"
}

### Get current user details
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout