### Create a car sale
POST http://localhost:3000/reports
content-type: application/json

{
    "make": "Ford",
    "model": "Focus",
    "year": 2022,
    "mileage": 12000,
    "lng": 0,
    "lat": 0,
    "price": 18000
}

### Approve report
PATCH http://localhost:3000/reports/1
content-type: application/json

{
    "approved": true
}

### Get an esitmate for an existing vehicle
GET http://localhost:3000/reports?make=ford&model=focus&lng=0&lat=0&year=1980&mileage=20000
